include = [
  "./Sublime/CreateThings/**/*.py",
  "./Sublime/SnippedYa/bootstrap_four.py",
  "./Sublime/SnippedYa/tools.py",
  "./Sublime/link_pkgs.py",
  "./install.py",
  "./zsh/bin/pipx-outdated-py"
]
[lint]
extend-select = ["I"]

[lint.isort]
known-third-party = ["sublime", "sublime_plugin"]