# Starship Shell Configuration
# https://starship.rs/config/

add_newline = false
command_timeout = 650

[aws]
disabled = true

[character]
error_symbol = "[✘](bold red)"

[cmd_duration]
disabled = true

[directory]
truncation_length = 4
fish_style_pwd_dir_length = 1

[git_branch]
truncation_length = 6

[git_status]
modified = "[!$count](underline bright-purple)"
staged = "[+$count](underline bright-green)"
untracked = "[?$count](underline blue)"
renamed = "[»$count](bold cyan)"
deleted = "[✘$count](bold underline fg:197)"

[hostname]
disabled = false
ssh_only = true

[java]
disabled = true

[line_break]
disabled = false

[memory_usage]
disabled = true
threshold = 50

[nodejs]
disabled = false

[package]
disabled = false
display_private = true

[python]
pyenv_version_name = false
pyenv_prefix = ""

[ruby]
disabled = true

[time]
disabled = false
style = "bold yellow"
format = "[\\[$time\\]](bold yellow) "
time_format = "%j"  # Day of the year

[username]
show_always = false
