add_newline = true

[aws]
disabled = true

[character]
use_symbol_for_status = true

[cmd_duration]
disabled = true

[directory]
fish_style_pwd_dir_length = 1

[git_branch]
truncation_length = 6

[git_status]
modified_count = { enabled = true, style = "underline bright-purple" }
staged_count = { enabled = true, style = "underline bright-green" }
unstaged_count = { enabled = true, style = "underline yellow" }

[hostname]
disabled = false
ssh_only = true

[java]
disabled = true

[line_break]
disabled = false

[memory_usage]
disabled = true
show_percentage = true
show_swap = true
threshold = 50

[nodejs]
disabled = false

[package]
disabled = false
display_private = true

[python]
pyenv_version_name = false
scan_for_pyfiles = false
pyenv_prefix = ""

[ruby]
disabled = true

[time]
disabled = false
format = "[%j]"

[username]
show_always = false
