# Starship Configuration
# https://starship.rs/config/

add_newline = false
command_timeout = 850

[aws]
disabled = true

[character]
error_symbol = "[✘](bold red)"

[cmd_duration]
# disabled = true
# min_time = 250
show_milliseconds = true

[directory]
truncation_length = 3
fish_style_pwd_dir_length = 1

[git_branch]
truncation_length = 12

[git_status]
disabled = false
modified = "[!$count](underline bright-purple)"
staged = "[+$count](underline bright-green)"
untracked = "[?$count](underline blue)"
renamed = "[»$count](bold cyan)"
deleted = "[✘$count](bold underline fg:197)"

[java]
disabled = true

[memory_usage]
disabled = true
threshold = 50

[package]
display_private = true

[python]
pyenv_version_name = false
pyenv_prefix = ""

[ruby]
disabled = true

[time]
disabled = false
style = "bold yellow"
format = "[\\[$time\\]]($style) "
time_format = "%j" # Day of the year
